services:
  - type: web
    name: frogger-backend
    runtime: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
